### ISSUE TITLE
Lint option is not available

### ISSUE THREAD

**Issue by VladDvoryankin** [csscomb/grunt-csscomb#32]
Hi t32k, many thanks for your work on adaptation of csscomb for grunt.

I want to let you know that there is no way to use lint option for csscomb, 
because it's implemented only as cli attributes.
it would be good if this option could be moved to options object, 
or even to .csscomb.json config file (not sure that this issue should be placed in this thread)

**Comment by noahcooper** [comment]
Closing this issue as it was a core csscomb.js issue fixed in version 4.0.0.
