### ISSUE TITLE
console.warn stops CSScomb

### ISSUE THREAD

**Issue by tonyganch** [csscomb/grunt-csscomb#34]
If for some reason there is an unacceptable value in user's config, CSScomb [prints a warning to console](https://github.com/csscomb/core/blob/master/lib/core.js#L280):

``` js
try {
    addHandler(options[optionName], config[optionName]);
 } catch (e) {
    // Show warnings about illegal config values only in verbose mode:
    if (verbose) {
        console.warn('\nFailed to configure "%s" option:\n%s', optionName, e.message);
    }
}
```

Errors are thrown within `setValue` function: https://github.com/csscomb/core/blob/master/lib/core.js#L101

@corvannoorloos [says](https://github.com/csscomb/csscomb.js/issues/286) that instead of just printing a warning Grunt plugin also "discontinues the task (the files aren't being modified after this notice)".

**Comment by noahcooper** [comment]
I'm not able to reproduce the issue described. `console.warn` does not appear to cause Grunt to exit.
