### ISSUE TITLE
Cannot read property of undefined error for SASS files

### ISSUE THREAD

**Issue by acadet** [csscomb/grunt-csscomb#37]
Hi guys,

I am trying to format my SASS files but I have this warning:
`Cannot read property '0' of undefined`

I found [this ticket](https://github.com/tonyganch/gonzales-pe/issues/20) so I assume fixing is in progress. Some news?

Thanks in advance!

**Comment by noahcooper** [comment]
Closing old issues which appear to have already been fixed. Please reopen if you are still experiencing this problem.
