### ISSUE TITLE
Lift up property "border-color" above "border-bottom" (for example).

### ISSUE THREAD

**Issue by 1ike** [csscomb/grunt-csscomb#39]
In that case border-color will not aplly.

So you need write color in such ways:
border-bottom: {width} {style} {color};
or
border-bottom-color: ...;
border-bottom-width: ...;
border-bottom-style:  ...;

**Comment by wardpeet** [comment]
It's not really a grunt-csscomb issue, if it doesn't behave how it should than it's a csscomb issue. Grunt-csscomb is just a task around csscomb.

**Comment by discodanser** [comment]
You are right, I'll write to csscomb.js. 
But grunt task was a first link in the chain (and can link old version csscomb.js in "dependencies"  or somewhat else...).

**Comment by noahcooper** [comment]
Closing this issue as it is a core csscomb.js issue.
