### ISSUE TITLE
Cannot support the latest grunt version v1.0.0

### ISSUE THREAD

**Issue by liuzeyafzy** [csscomb/grunt-csscomb#44]
Hi, 
when I execute `sudo npm install grunt-csscomb --save-dev`,
I get this error: `npm ERR! peerinvalid Peer grunt-csscomb@3.1.0 wants grunt@^0.4.5`

Maybe `>=` is better than `^` in file `package.json`.

**Comment by marcovtwout** [comment]
It seems this issue is resolved in july: https://github.com/csscomb/grunt-csscomb/commit/9ed994a08e96e7e00e5269bf487a6aaacbbc396b
