### ISSUE TITLE
Security warning in csscomb@3.1.0 - Update csscomb package

### ISSUE THREAD

**Issue by lacymorrow** [csscomb/grunt-csscomb#45]
Regular Expression Denial of Service (DoS)SEVERITY: HIGH
Discovered in a nested dependency: 
grunt-csscomb@3.1.1 -> csscomb@3.1.8 -> csscomb-core@3.0.0-3.1 -> **minimatch@0.2.12**

Details: https://snyk.io/vuln/npm:minimatch:20160620?utm_source=bithound

minimatch > 3.0.2 should be used, updating to the latest csscomb is recommended

**Comment by noahcooper** [comment]
Fixed in v4.0.0.
